services:
  api:
    build:
      context: . 
      dockerfile: CoursesApi/Dockerfile
    container_name: courses-api
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=coursesdb;Username=postgres;Password=postgres;
    depends_on:
      db:
        condition: service_healthy 
        
  db:
    image: postgres:latest 
    container_name: courses-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=coursesdb
    ports:
      - "5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coursesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
